apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: hisd3-middleware
  spec:
    type: ClusterIP
    ports:
    - name: http
      port: 80
      targetPort: 4567
      protocol: TCP
    selector:
      app: hisd3-middleware
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: special-config
  data:
    hisd3.smburl   : "smb://127.0.0.1/shared"
    hisd3.hisd3Port: "8080"